### PR TITLE
feat: basic Kickplan adapter

### PR DESCRIPTION
**Pull request by chuhlomin**
This PR adds implementation for a few Kickplan HTTP adapter methods:

* BooleanEvaluation
* StringEvaluation
* Int64Evaluation
* ObjectEvaluation
* SetMetric
* IncMetric
* DecMetric

Also, a few tests added to ensure that important headers are passed to the HTTP client, and that response is parsed correctly.

### CODE REVIEW

**Review by BJClark — APPROVED** [review]
I noticed there's no object feature type, and you had questions about that before and suggested maybe just returning the json object instead of a Go object.
1. I think that's probably fine for now, if you want to stub that in.
2. What does the go implementations of OpenFeature do?

Otherwise this looks good, I think you've got most of it in here.

**Comment by BJClark** [comment]
@jaredhoyt you might want to take a look at this because it's got some metrics stuff in it.

**Comment by chuhlomin** [comment]
1. I added an object evaluation method. In Go, working with objects with unknown structures is not that convenient. I recommend the [mapstructure](https://github.com/mitchellh/mapstructure) package to decode `interface{}` into the Go structure that represents the object flag. It may look like this:

    ```go
    client := NewClient()
    obj, err = client.GetObject(context.TODO(), "my-flag", interface{}, nil)
    if err != nil { ... }
    
    type MyObject struct {
      Field string
    }
    var myObj MyObject
    
    err := mapstructure.Decode(obj, &myObj)
    if err != nil { ... }
    ```

2. OpenFeature Go SDK provides a similar way of resolving feature flags. It doesn't support metrics or setting flag values. What is called `adapter` in this repository, called `provider` in OpenFeature SDK. There are several [implemented adapters](https://github.com/open-feature/go-sdk-contrib/tree/main/providers) already.

**Review by BJClark — APPROVED** [review]

**Comment by BJClark** [comment]
Re:mapstructure makes sense to me.

**Pull request merged**
